App\Entity\User:
    properties:
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
        password:
            - NotBlank: ~
App\Entity\Video:
    properties:
        nom:
            -NotBlank: ~
        title:
            -NotBlank: ~
        description:
            -NotBlank: ~
        genre:
            -NotBlank: ~